version: '3.4'

services: 
  service-product:
   # container_name: spring-app
    image: springbooot-app
    restart: always
    build: ./ManagerProducts
    ports:
      - 8802:8802 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: khanhly1
      MYSQL_PORT: 3306

  service-discolary:
   # container_name: spring-app
    image: discolary
    restart: always
    build: ./Microservice-Service-Registry
    ports:
      - 8761:8761 
  service-gateway:
   # container_name: spring-app
    image: gateway
    restart: always
    build: ./ServiceGateway
    ports:
      - 8803:8803 
  service-config-server:
   # container_name: spring-app
    image: container_name
    restart: always
    build: ./SpringConfigServer
    ports:
      - 8888:8888
  mysqldb: 
    container_name: mysqldb
    image: mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: lamdocker
      MYSQL_ROOT_PASSWORD: khanhly1
  redis-spring-boot:
    image: redis:alpine
    ports:
      - 6380:6379
    tty: true

