resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 15
        limitRefreshPeriod: 1s
        timeoutDuration: 100ms
      backendAConfig:
        limitForPeriod: 5
        limitRefreshPeriod: 50s
        timeoutDuration: 100ms
    instances:
      findAllUser:
        baseConfig: backendAConfig
      backendB:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 100ms